---
title: "Simulations"
author: E. Brennan Bollman
date: '`r format(Sys.time(), "%y-%m-%d")`'
output: github_document
---

```{r setup, INCLUDE = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom")) 

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d()
scale_fill_discrete = scale_fill_viridis_d()
```

## Sample simulation

Function

```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 4) {
  
  sim_data = 
    tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
    )

  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}
```

Simulate by running this line

```{r}
sim_mean_sd(30)
```

## Let's simulate a lot

Start with a `for` loop.

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(samp_size = 30)
  
}

bind_rows(output)

```

This Above doesn't have input list, just has output list.
Can use map to apply input list to a function for output list

Let's use a loop function.

```{r}
sim_results = 
  rerun(100, sim_mean_sd(samp_size = 30)) %>% 
  bind_rows()
```

Can set the `set.seed` to make sure the random sample is same each time?

Let's look at results

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) + geom_density()

sim_results %>% 
  summarize(
    avg_samp_mean = mean(mean),
    sd_samp_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) + geom_density()
```

