---
title: "Writing functions"
author: E. Brennan Bollman
date: '`r format(Sys.time(), "%y-%m-%d")`'
output: github_document
---

```{r setup, INCLUDE = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom")) 

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d()
scale_fill_discrete = scale_fill_viridis_d()
```


## Do something simple

Convert sample into collection of Z scores (subtract mean and divide by standard deviation). Start by writing code to do the thing you want to do and then make it a function.

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Want function to compute z-scores

```{r}
z_scores = function(x) {
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  return(z)
}

z_scores(x_vec)
```

Input = x_vec
function operates on x

Try function on other things. These should give errors.

```{r error = TRUE}
z_scores(3)
z_scores("my name is jeff")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

Can't take mean of character vector or dataset
